title: <p align="center"> VIJAYA BHASKAR BANALA </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="/assets/VIJAYA_BHASKAR_BANALA_resume.pdf">Resume</a> |
  <a href="https:www.linkedin.com/in/vijayabhaskar112">LinkedIn</a> |
  <a href="https://github.com/VJ0216">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
